### ISSUE TITLE
Default port for connection when URL has no port specified

### ISSUE THREAD

**Issue by ecton** [khonsulabs/fabruic#15]
I am frustrated to admit it took me entirely too long to figure out why my server example was broken despite all my unit tests succeeding. In simplifying my code, I removed part of the code where it would set a default port if the URL didn't specify one. I'm not sure how you're picking a port, but you're not picking the port I want :)

This is a question, not a request: Should we add a way to set the default port for a client fabruic connection, or should I modify the URL before passing it along?

**Comment by daxpedda** [comment]
Fabruic is not picking a port, in fact if you don't give it a port, it will return an error.
But because of a [limitation in URL](https://docs.rs/url/2.2.1/url/struct.Url.html#method.port), there is always gonna be a default port for known schema unless you define otherwise.

Known schemas are `http`, `https`, `ws`, `wss` and `ftp`.

What did you do exactly to trigger that behavior? I am assuming that you just didn't specify a port at all? But that should have failed. If you did specify a port and it picked a different one, that would be a bug in Fabruic.

**Comment by daxpedda** [comment]
Potentially one way to help out library consumers, an idea would be to provide a mapping interface for schemas to ports in the builder configuration.
